conv_cur/conv_cur/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('converter.urls', namespace='converter')),
]

conv_cur/converter/urls.py
from django.urls import path

from .views import get_convert

app_name = 'converter'

urlpatterns = [
    path('', get_convert, name='index'),
]

conv_cur/converter/views.py
import requests
from django.conf import settings
from django.shortcuts import render


def get_convert(request):
    response = requests.get(f'https://api.currencyapi.com/v3/latest?apikey={settings.API_KEY}').json()
    currencies = response.get('data')

    if request.method == 'POST':
        from_amount = request.POST.get('from-amount')
        if from_amount:
            from_curr = request.POST.get('from-curr')
            to_curr = request.POST.get('to-curr')

            converted_amount = round(currencies[to_curr]['value'] / currencies[from_curr]['value'] * float(from_amount), 2)

            context = {
                'from_curr': from_curr,
                'from_amount': from_amount,
                'to_curr': to_curr,
                'converted_amount': converted_amount,
                'currencies': currencies,
            }
            return render(request=request, template_name='converter/index.html', context=context)

    context = {'currencies': currencies}
    return render(request=request, template_name='converter/index.html', context=context)

conv_cur/converter/templates/converter/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ title }}
{% endblock %}


{% block content %}

    <div class="logo_box">
        <img src="{% static 'img/logo/logo4.png' %}" alt="Изображение логотипа">
    </div>

    <div class="container">
        <div class="row">
            <div class="card box-shadow m-2 form-wrap">
                <div class="card-header text-center">
                    <h3>Конвертер валют</h3>
                </div>
                <form id="form" class="p-3" action="{% url 'converter:index' %}" method="post">
                    {% csrf_token %}

                    <div class="form-row">

                        <div class="form-group col-md-4 mb-0">
                            <label for="amount">Сумма*</label>
                            <input id='amount' type="number" class="form-control" required placeholder="Введите число" {% if from_amount %} value="{{ from_amount }}" {% endif %} name="from-amount">
                        </div>

                        <div class="form-group col-md-4 mb-0">
                            <label for="from_curr">Отдаем*</label>
                            <select class="form-control" id="from_curr" name="from-curr" value="{{ from_curr }}">
                                {% for curr in currencies %}
                                    <option value="{{ curr }}" {% if from_curr == curr %}selected{% endif %}>{{ curr }}</option>
                                {% endfor %}
                            </select>
                        </div>

                        <div class="form-group col-md-4 mb-0">
                            <label for="to-curr">Получаем*</label>
                            <select class="form-control" id="to-curr" name="to-curr" value="{{ to_curr }}">
                                {% for curr in currencies %}
                                    <option value="{{ curr }}" {% if to_curr == curr %}selected{% endif %}>{{ curr }}</option>
                                {% endfor %}
                            </select>
                        </div>

                    </div>
                    <hr>
                    {% if converted_amount %}
                        <div class="card col-6 p-0 m-auto">
                            <div class="card-header text-center">
                                    <h5>Отдаем <b>{{ from_curr }}</b> Получаем
                                        <b>{{ to_curr }}</b></h5>
                            </div>
                            <div class="card-body">
                                {{ converted_amount }}
                            </div>
                        </div>
                    {% endif %}
                    <div class="submit-btn mt-3">
                        <button type="submit" class="btn btn-primary">Рассчитать</button>
                    </div>
                </form>

            </div>
        </div>
    </div>

{% endblock %}

conv_cur/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href=" {% static 'css/normalize.css' %}">
    <link rel="stylesheet" href=" {% static 'css/reset.css' %}">
    <link rel="stylesheet" href=" {% static 'css/converter.css' %}">
</head>
<body>
    {% block content %}

    {% endblock %}
</body>
</html>